version: '3.8'

services:

  db:
    image: postgres:16
    container_name: servicematchDB
    restart: always
    environment:
      POSTGRES_USER: servimatch_user
      POSTGRES_PASSWORD: servimatch123
      POSTGRES_DB: servimatch_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U servimatch" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: servimatch-app
#    depends_on:
#      db:
#        condition: service_healthy
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/servimatch
#      SPRING_DATASOURCE_USERNAME: servicematch_user
#      SPRING_DATASOURCE_PASSWORD: servimatch123
#      JWT_SECRET: ${JWT_SECRET:-ThisIsAVerySecureSecretKeyForJWTTokenGenerationPleaseChangeInProduction}
#    ports:
#      - "8080:8080"
#    restart: unless-stopped

volumes:
  db_data: